import io
import sqlite3
import json
import os
from fastapi import FastAPI, File, UploadFile, HTTPException
from pypdf import PdfReader
from google import genai
from google.genai import types
from groq import Groq
from dotenv import load_dotenv

# Load hidden keys from the local .env file
load_dotenv()

# --- API CLIENT SETUP ---
gemini_client = genai.Client(api_key=os.getenv("GEMINI_API_KEY"))
groq_client = Groq(api_key=os.getenv("GROQ_API_KEY"))
# ------------------------

app = FastAPI()

# --- DATABASE SETUP ---
def init_db():
    conn = sqlite3.connect("flashcards.db")
    cursor = conn.cursor()
    
    cursor.execute('''
        CREATE TABLE IF NOT EXISTS decks (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            name TEXT NOT NULL
        )
    ''')
    
    cursor.execute('''
        CREATE TABLE IF NOT EXISTS cards (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            deck_id INTEGER,
            front TEXT NOT NULL,
            back TEXT NOT NULL,
            FOREIGN KEY (deck_id) REFERENCES decks (id)
        )
    ''')
    conn.commit()
    conn.close()

init_db()
# ----------------------

@app.get("/")
def read_root():
    return {"message": "The AI Study Backend is alive!"}

@app.post("/upload/")
async def upload_document(file: UploadFile = File(...)):
    if not file.filename.endswith(".pdf"):
        raise HTTPException(status_code=400, detail="Only PDF files are allowed.")
    
    # 1. Read and Extract Text
    contents = await file.read()
    pdf_file = io.BytesIO(contents)
    reader = PdfReader(pdf_file)
    
    extracted_text = ""
    for page in reader.pages:
        text = page.extract_text()
        if text:
            extracted_text += text + "\n"

    if not extracted_text.strip():
         raise HTTPException(status_code=400, detail="Could not extract text from this PDF.")
         
    # 2. Prepare Prompts and Schemas
    # Gemini requires a specific schema dictionary
    gemini_schema = {
        "type": "ARRAY",
        "items": {
            "type": "OBJECT",
            "properties": {
                "front": {"type": "STRING"},
                "back": {"type": "STRING"}
            },
            "required": ["front", "back"]
        }
    }
    
    # Groq needs explicit instructions in the prompt to return JSON
    base_prompt = f"Create 5 high-quality flashcards summarizing this text:\n\n{extracted_text}"
    groq_prompt = base_prompt + "\n\nReturn ONLY a valid JSON array of objects. Each object must have exactly two keys: 'front' and 'back'."
    
    try:
        # --- ATTEMPT 1: GEMINI API ---
        response = gemini_client.models.generate_content(
            model='gemini-3.6-flash',
            contents=base_prompt,
            config=types.GenerateContentConfig(
                response_mime_type="application/json",
                response_schema=gemini_schema,
            ),
        )
        flashcards_data = json.loads(response.text)
        message = "Success: Flashcards generated by Gemini API and saved!"
        
    except Exception as gemini_error:
        print(f"Gemini API Error: {gemini_error}")
        print("Switching to Backup AI (Groq)...")
        
        try:
            # --- ATTEMPT 2: GROQ API (BACKUP) ---
            chat_completion = groq_client.chat.completions.create(
                messages=[
                    {"role": "system", "content": "You are an assistant that outputs strictly valid JSON arrays."},
                    {"role": "user", "content": groq_prompt}
                ],
                model="llama-3.3-70b-versatile",
                response_format={"type": "json_object"}
            )
            
            # Groq's JSON mode returns an object containing the array, so we parse it safely
            raw_response = chat_completion.choices[0].message.content
            
            # Simple cleanup in case Groq wraps the array in a parent object
            parsed_json = json.loads(raw_response)
            if isinstance(parsed_json, dict):
                # Find the first array value inside the object
                flashcards_data = next(iter(parsed_json.values()))
            else:
                flashcards_data = parsed_json
                
            message = "Gemini was busy. Success: Flashcards generated by Groq API and saved!"

        except Exception as groq_error:
            # --- ATTEMPT 3: FALLBACK TO DUMMY DATA ---
            print(f"Groq API Error: {groq_error}")
            flashcards_data = [
                {"front": "What is JavaScript?", "back": "A scripting language for web pages."},
                {"front": "What is PHP?", "back": "A server-side scripting language."}
            ]
            message = "Both APIs failed. Saved fallback test flashcards instead."

    # --- DATABASE SAVING LOGIC ---
    conn = sqlite3.connect("flashcards.db")
    cursor = conn.cursor()
    
    deck_name = file.filename.replace(".pdf", "")
    cursor.execute("INSERT INTO decks (name) VALUES (?)", (deck_name,))
    deck_id = cursor.lastrowid
    
    for card in flashcards_data:
        # Ensure we are inserting strings safely
        front_text = card.get("front", "")
        back_text = card.get("back", "")
        if front_text and back_text:
            cursor.execute(
                "INSERT INTO cards (deck_id, front, back) VALUES (?, ?, ?)",
                (deck_id, front_text, back_text)
            )
        
    conn.commit()
    conn.close()
    # -----------------------------

    return {
        "filename": file.filename,
        "deck_id": deck_id,
        "cards_saved": len(flashcards_data),
        "message": message
    }

@app.get("/decks/")
def get_all_decks():
    conn = sqlite3.connect("flashcards.db")
    cursor = conn.cursor()
    cursor.execute("SELECT id, name FROM decks")
    decks = [{"id": row[0], "name": row[1]} for row in cursor.fetchall()]
    conn.close()
    return {"decks": decks}

@app.get("/decks/{deck_id}/cards/")
def get_deck_cards(deck_id: int):
    conn = sqlite3.connect("flashcards.db")
    cursor = conn.cursor()
    cursor.execute("SELECT id, front, back FROM cards WHERE deck_id = ?", (deck_id,))
    cards = [{"id": row[0], "front": row[1], "back": row[2]} for row in cursor.fetchall()]
    conn.close()
    
    if not cards:
        raise HTTPException(status_code=404, detail="Deck not found or has no cards.")
        
    return {"deck_id": deck_id, "cards": cards}